#!/bin/python

#go to https://trinket.io/library/trinkets/b7ddd0c0b6 to create random passwords

import random

chars = "abcdefghijklmnopqrstuvwxyz1234567890!?.,-"

number = input('number of passwords?')
number = int(number)

length = input('password length?')
length = int(length)

for r in range(number): #number random passwords you want
    password = ''
    for c in range(length):
        password += random.choice(chars)
    print(password)
