#!/bin/python3

#To test code go https://duroak_1688.trinket.io/sites/tcards_py

from random import *
from turtle import *

screen = Screen()
screen.bgcolor('white')
penup()
hideturtle()
speed(10)

def bgcolor():
  red = randint(20, 235)
  green = randint(20, 235)
  blue = randint(20, 235)
  color(red, green, blue)
  
def border():
  bgcolor()
  length = 215
  height = 300
  begin_fill()
  forward(length)
  right(90)
  forward(height)
  right(90)
  forward(length)
  right(90)
  forward(height)
  right(90)
  end_fill()
  
def picframe():
  color('white')
  length = 165
  height = 155
  begin_fill()
  forward(length)
  right(90)
  forward(height)
  right(90)
  forward(length)
  right(90)
  forward(height)
  right(90)
  end_fill()
  
characters = {}

file = open('cards.txt', 'r')

for line in file.read().splitlines():
  name, attack, defence, intelligence, image = line.split(', ')
  characters[name] = [attack, defence, intelligence, image]
  screen.register_shape(image)

file.close()

while True:
  
  character = input('Choose a "Rick and Morty" character: ')
  
  if character == "random": 
    character = choice(list(characters.keys()))
    print(character)
    
  if character in characters:
    stats = characters[character]
    #goto(-105, 210)
    #border()
    #goto(-80, 165)
    #picframe()
    clear()
    color('black')
    style = ('Comic Sans MS', 14, 'bold')
    goto(-95, 180)
    write(character, font=style, align='left')
    goto(0, 90)
    shape(stats[3])
    setheading(90)
    stamp()
    setheading(-90)
    forward(100)
    write('ATK: ' + stats[0], font=style, align='center')
    forward(25)
    write('DEF: ' + stats[1], font=style, align='center')
    forward(25)
    write('Intel: ' + stats[1], font=style, align='center')
  
  else:
    print('character doesn\'t exist')
